name: email_and_phone_verification
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  after_layout: ^1.2.0
  country_picker: ^2.0.19
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  fzregex: ^2.0.0
  get: ^4.6.5
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true